# tasks file for mysql_db
        #    - name: Download mysql repo
        #      get_url:
        #        url: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
        #        dest: /tmp/mysql-community-release-el7-5.noarch.rpm
    - name: Install MySQL repo
      yum:
        name: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
        state: present

    - name: Install MySQL database
      yum:
        name: ['mysql-server']
        state: present

    - name: Start MySQL service
      ansible.builtin.systemd:
        name: mysqld
        state: started
        enabled: yes
        masked: no

    - name: Create Application Database
      mysql_db:
        name: "{{ db_name }}"
        state: present

    - name: Create Database User
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: '*.*:ALL'
        state: present

